# Generated by Django 4.2.4 on 2023-10-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_num',
        ),
    ]
