# Generated by Django 4.2.4 on 2023-10-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_rename_phone_customer_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
